### ISSUE TITLE
sorry, but how can i use in mac environment?

### ISSUE THREAD

**Issue by whrenstone** [Ziyadsk/scc#2]
Hi, i run the install  the install script as it was told, but it shows that scc command is not found

**Comment by Ziyadsk** [comment]
it normally should work , it was developed and tested on a mac . try closing fully the terminal emulator and retry .

**Comment by whrenstone** [comment]
Thanks for your quick reply. I have already closed the terminal emulator and then restarted the mac, but  scc command still not found when i run it in the terminal .I guess something wrong with the system  environment?

**Comment by Ziyadsk** [comment]
echo your $PATH , and see if the command is there .

**Comment by whrenstone** [comment]
Thanks for your advice, but the command is not there, and just a bunch of :/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin::

**Comment by Ziyadsk** [comment]
that means that you didn't run the install script correctly with 
 ``` shell 
sudo ./install.sh
```
anyway , check also your home dir for the .scc directory .

**Comment by whrenstone** [comment]
@Ziyadsk   it seems that i must add source ~/.bashrc; source ~/.zshrc;  in install.sh script to make it work

**Comment by Ziyadsk** [comment]
@whrenstone oh yeah , i forgot to mention that , because in the install script i export scc to the $PATH and write into your bashrc files , which are reloaded ( sourced ) everytime your start your terminal .

**Comment by whrenstone** [comment]
Great! Thanks for your sharing!  Really helpful!
